export enum CATEGORY {
  DailyNews = 'daily-news',
  VideoNews = 'video-news',
  StoryWorld = 'story-world',
  ChildrensArena = 'childrens-arena',
  Health = 'health',
  Medical = 'medical',
  Columns = 'columns',
  Talent = 'talent',
  Achievements = 'achievements',
  Society = 'society',
  Reflection = 'reflection',
  Articles = 'articles',
  Cooking = 'cooking',
  Social = 'social',
  LifeTreasure = 'life-treasure',
  Editorial = 'editorial',
  MAGAZINE = 'magazine',
  HomeTopAd = 'home-top-ad',
  HomeMiddleAd = 'home-middle-ad',
  HomeBottomAd = 'home-bottom-ad',
  DetailTopAd = 'detail-top-ad',
  DetailBottomAd = 'detail-bottom-ad',
  DetailSideAd = 'detail-side-ad',
}
