export enum CATEGORY {
  DailyNews = 'daily-news',
  VideoNews = 'video-news',
  StoryWorld = 'story-world',
  ChildrensArena = 'childrens-arena',
  Health = 'health',
  Medicine = 'medicine',
  Columns = 'columns',
  Talent = 'talent',
  Achievements = 'achievements',
  Society = 'society',
  Reflection = 'reflection',
  Articles = 'articles',
  Cooking = 'cooking',
  Social = 'social',
  LifeTreasure = 'life-treasure',
  Editorial = 'editorial',
}
